#ifndef _STD4573_INCLUDE_REGISTER
	#error "You must define _STD4573_INCLUDE_REGISTER macro before include this file"
#endif

#ifdef _STD4573_INCLUDE_REGISTER
	Register(NONE,"NONE")
	
	Register(AL,"AL")
	Register(CL,"CL")
	Register(DL,"DL")
	Register(BL,"BL")
	Register(AH,"AH")
	Register(CH,"CH")
	Register(DH,"DH")
	Register(BH,"BH")
	Register(SPL,"SPL")
	Register(BPL,"BPL")
	Register(SIL,"SIL")
	Register(DIL,"DIL")
	Register(R8B,"R8B")
	Register(R9B,"R9B")
	Register(R10B,"R10B")
	Register(R11B,"R11B")
	Register(R12B,"R12B")
	Register(R13B,"R13B")
	Register(R14B,"R14B")
	Register(R15B,"R15B")
	
	Register(AX,"AX")
	Register(CX,"CX")
	Register(DX,"DX")
	Register(BX,"BX")
	Register(SP,"SP")
	Register(BP,"BP")
	Register(SI,"SI")
	Register(DI,"DI")
	Register(R8W,"R8W")
	Register(R9W,"R9W")
	Register(R10W,"R10W")
	Register(R11W,"R11W")
	Register(R12W,"R12W")
	Register(R13W,"R13W")
	Register(R14W,"R14W")
	Register(R15W,"R15W")
	
	Register(EAX,"EAX")
	Register(ECX,"ECX")
	Register(EDX,"EDX")
	Register(EBX,"EBX")
	Register(ESP,"ESP")
	Register(EBP,"EBP")
	Register(ESI,"ESI")
	Register(EDI,"EDI")
	Register(R8D,"R8D")
	Register(R9D,"R9D")
	Register(R10D,"R10D")
	Register(R11D,"R11D")
	Register(R12D,"R12D")
	Register(R13D,"R13D")
	Register(R14D,"R14D")
	Register(R15D,"R15D")
	
	Register(RAX,"RAX")
	Register(RCX,"RCX")
	Register(RDX,"RDX")
	Register(RBX,"RBX")
	Register(RSP,"RSP")
	Register(RBP,"RBP")
	Register(RSI,"RSI")
	Register(RDI,"RDI")
	Register(R8,"R8")
	Register(R9,"R9")
	Register(R10,"R10")
	Register(R11,"R11")
	Register(R12,"R12")
	Register(R13,"R13")
	Register(R14,"R14")
	Register(R15,"R15")
	
	Register(ES,"ES")
	Register(CS,"CS")
	Register(SS,"SS")
	Register(DS,"DS")
	Register(FS,"FS")
	Register(GS,"GS")
	
	Register(CR0,"CR0")
	Register(CR1,"CR1")
	Register(CR2,"CR2")
	Register(CR3,"CR3")
	Register(CR4,"CR4")
	Register(CR5,"CR5")
	Register(CR6,"CR6")
	Register(CR7,"CR7")
	Register(CR8,"CR8")
	Register(CR9,"CR9")
	Register(CR10,"CR10")
	Register(CR11,"CR11")
	Register(CR12,"CR12")
	Register(CR13,"CR13")
	Register(CR14,"CR14")
	Register(CR15,"CR15")
	
	Register(DR0,"DR0")
	Register(DR1,"DR1")
	Register(DR2,"DR2")
	Register(DR3,"DR3")
	Register(DR4,"DR4")
	Register(DR5,"DR5")
	Register(DR6,"DR6")
	Register(DR7,"DR7")
	Register(DR8,"DR8")
	Register(DR9,"DR9")
	Register(DR10,"DR10")
	Register(DR11,"DR11")
	Register(DR12,"DR12")
	Register(DR13,"DR13")
	Register(DR14,"DR14")
	Register(DR15,"DR15")
	
	Register(MM0,"MM0")
	Register(MM1,"MM1")
	Register(MM2,"MM2")
	Register(MM3,"MM3")
	Register(MM4,"MM4")
	Register(MM5,"MM5")
	Register(MM6,"MM6")
	Register(MM7,"MM7")
	
	Register(ST0,"ST0")
	Register(ST1,"ST1")
	Register(ST2,"ST2")
	Register(ST3,"ST3")
	Register(ST4,"ST4")
	Register(ST5,"ST5")
	Register(ST6,"ST6")
	Register(ST7,"ST7")
	
	Register(XMM0,"XMM0")
	Register(XMM1,"XMM1")
	Register(XMM2,"XMM2")
	Register(XMM3,"XMM3")
	Register(XMM4,"XMM4")
	Register(XMM5,"XMM5")
	Register(XMM6,"XMM6")
	Register(XMM7,"XMM7")
	Register(XMM8,"XMM8")
	Register(XMM9,"XMM9")
	Register(XMM10,"XMM10")
	Register(XMM11,"XMM11")
	Register(XMM12,"XMM12")
	Register(XMM13,"XMM13")
	Register(XMM14,"XMM14")
	Register(XMM15,"XMM15")
	
	Register(YMM0,"YMM0")
	Register(YMM1,"YMM1")
	Register(YMM2,"YMM2")
	Register(YMM3,"YMM3")
	Register(YMM4,"YMM4")
	Register(YMM5,"YMM5")
	Register(YMM6,"YMM6")
	Register(YMM7,"YMM7")
	
	Register(YMM8,"YMM8")
	Register(YMM9,"YMM9")
	Register(YMM10,"YMM10")
	Register(YMM11,"YMM11")
	Register(YMM12,"YMM12")
	Register(YMM13,"YMM13")
	Register(YMM14,"YMM14")
	Register(YMM15,"YMM15")
				
	Register(RIP,"RIP")
#endif