//Last Modified At 2025/09/10
//@Version 1.0.0.0
#ifndef _STDEX_IGNORE_WARNINGS
#define _STDEX_IGNORE_WARNINGS
#define _STDEX_IGNORE_BITMASK_FLAGS_WARNINGS
#define _STDEX_IGNORE_BITWISE_BIT_WRITER_WARNINGS
#endif