//Last Modified At 2026/03/16
//@Version 1.0.0.0
#ifndef _STDEX_IGNORE_WARNINGS

#define _STDEX_IGNORE_WARNINGS
#define _STDEX_IGNORE_BITMASK_FLAGS_WARNINGS
#define _STDEX_IGNORE_BITWISE_BIT_WRITER_WARNINGS
#define _STDEX_IGNORE_STRUCTURE_SLOT_MAP_ID_WARNINGS
#define _STDEX_IGNORE_STRUCTURE_SLOT_MAP_ID_REF_WARNINGS
#define _STDEX_IGNORE_META_REFLECT_WARNINGS

#endif